name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
body:
  - type: input
    id: gyroflow-version
    attributes:
      label: Gyroflow version
      description: What version of Gyroflow are you running?
      placeholder: Version nr or commit id
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: What operating system are you using?
      description: Please be specific, for example "macOS Catalina 10.15.4"
      placeholder: OS and version nr
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: What GPU are you using?
      description: If you are using a GPU please tell us what model you have.
      placeholder: Brand and model
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false