blank_issues_enabled: true
contact_links:
  - name: Gyrflow website
    url: https://gyroflow.xyz/
    about: Gyroflow website with general info
  - name: Gyrflow documentation
    url: https://docs.gyroflow.xyz/
    about: Please read the docs here